### ISSUE TITLE
Using virtualenv on mac osx 10.11 fails 

### ISSUE THREAD

**Issue by idkjs** [algolia/mongo-connector#20]
Though not specifically related to your software, the workflow suggested for this project fails at the point that i try to run ./env/bin/python setup.py install in the virtualenv .env folder. I get the following error:
build/temp.macosx-10.11-x86_64-2.7/_openssl.c:431:10: fatal error: 
'openssl/aes.h' file not found
# include

I tried running env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography in my user root and also inside my virtualenv environement, the running ./env/bin/python setup.py install inside my env folder. Still doesn't work. Perhaps the solution is no longer viable on 10.11? Any ideas? Thank you.

**Comment by redox** [comment]
Right, I just reproduced the issue as well :/ OpenSSL is always mess on OS X...

Seems that there is a discussion about it here: https://github.com/pyca/cryptography/issues/2138 and I managed to fix it by upgrading `pip`:

``` sh
$ git clone https://github.com/algolia/mongo-connector.git
$ cd mongo-connector
$ virtualenv env
$ ./env/bin/pip install --upgrade pip
$ ./env/bin/python setup.py install
```

Let me know if that doesn't work!
