### ISSUE TITLE
stable branch?

### ISSUE THREAD

**Issue by benjamine** [algolia/mongo-connector#6]
I just noticed `algolia` has become the default branch of this repo (not master), and that branch just received a big merge from 10gen-labs upstream repo, breaking many things (eg. doc_manager now is specified by name and not by file path, or `TypeError: upsert() takes at most 3 arguments (4 given)`).
Is there a branch we can consider stable? (maybe master should be the default branch?)

**Comment by redox** [comment]
Hi @benjamine,

thank you for reaching out. The `algolia` branch has always been the default branch. I've merged 10gen's  `master` branch earlier today and adapt the tests but it seems it's not enough. Let me check that now.

**Comment by redox** [comment]
@benjamine could you try again and let us know how it goes?

**Comment by benjamine** [comment]
ok, I'm creating separate issues.
